name: exclusive_barber
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 # Agrega esta línea
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  cached_network_image: ^3.4.1
  firebase_core: ^4.14.0
  cloud_firestore: ^6.9.0
  firebase_storage: 13.5.0
  image_picker: ^1.1.2
  firebase_auth: ^6.6.1
  url_launcher: ^6.3.2
  pdf: ^3.13.0
  printing: ^5.15.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo1.png
    - assets/images/corte.png
      